logging:
  level:
    root: info
    com.tutelary: debug
    io.netty: debug

server:
  port: 9988

storage:
  h2:
    properties:
      url: ${TUTELARY_STORAGE_H2_URL:jdbc:h2:mem:tutelary}
      username: ${TUTELARY_STORAGE_H2_USERNAME:root}
  mysql:
    properties:
      url: ${TUTELARY_STORAGE_MYSQL_URL:jdbc:mysql://127.0.0.1:3306/tutelary}
      username: ${TUTELARY_STORAGE_MYSQL_USERNAME:root}
      password: ${TUTELARY_STORAGE_MYSQL_PASSWORD:123456}

spring:
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      connection-test-query: select 1