logging:
  level:
    root: info
    com.tutelary: debug
    io.netty: debug

server:
  port: 9988

storage:
  h2:
    properties:
      url: ${TUTELARY_STORAGE_H2_URL:jdbc:h2:mem:tutelary}
      username: ${TUTELARY_STORAGE_H2_USERNAME:root}
  mysql:
    properties:
      url: ${TUTELARY_STORAGE_MYSQL_URL:jdbc:mysql://127.0.0.1:3306/tutelary}
      username: ${TUTELARY_STORAGE_MYSQL_USERNAME:root}
      password: ${TUTELARY_STORAGE_MYSQL_PASSWORD:123456}

spring:
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      connection-test-query: select 1
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: _tt
  # token有效期，单位s 默认1天, -1代表永不过期
  timeout: 108000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: tik
  # 是否输出操作日志
  is-log: true